name: Automated github actions

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  automated-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run automation script
        run: python .github/automation/script.py

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"   

      - name: Install yarn (previously npm) dependencies
        run: yarn install

      - name: Build dashboard
        run: yarn build